version: '3.3'
services:
  rabbitmq:
    container_name: rabbit-mq
    ports:
      - '8080:15672'
      - '5671:5671'
      - '5672:5672'
      - '15672:15672'
      - '25672:25672'
    image: 'rabbitmq:3-management-alpine'
  mongo:
    container_name: db
    ports:
      - '27017:27017'
    volumes:
      - '~/data:/data/db'
    image: mongo
